### ISSUE TITLE
Duplicate case field changes properties of related objects possibly unintentionally

### ISSUE THREAD

**Issue by JackReevies** [hmcts/flex-ui#35]
### Scenario

When duplicating the field `etICHearingAlreadyListed` from Scotland into England, the app also copied `initialConsideration` event  from Scotland, overwriting the existing entry in England. This resulted in the DisplayOrder of the event being changed unintentionally (but could feasibly change other fields if they were different). 

### Why this happens

When duplicating a CaseField there will be other objects it relies on to work so the app will scan for any dependencies (ie, the event it belongs to) and copy those over too. This works well when creating brand new fields, but can have unintentional side effects when the intention is just to modify an exiting field. 

### What can we do about it?

Could add some conditional logic that does not copy an object if its found to already exist, or ask the user. Concerned that the app might become a bit bloated at that point.

**Comment by Itay-Kirsh** [comment]
I think it's fine to add the logic.
You only need to check whether the fields in a duplicated field's _ID_ have existing entries in the new repo.

**Comment by JackReevies** [comment]
Only downside is that it breaks the original ethos that session data contains everything you need to get something working regardless of the state of the JSONs, but I think that might be a bit of a pipedream anyway.

So what should happen is it scans for everything needed to make that field show up (ie, events, authorisations, eventToFields, even other fields it may reference) and dumps that in the session file so that the session file can be replayed on any branch/state of the configs and it should work. But I'm no longer seeing the benefit in this over just storing the new stuff that would build upon the branch you were on when you created it.

It might be worth creating another story to remove this functionality in other places as it could get inconsistent/confusing for the user. For example, I used the tool to modify an existing field in scotland, but the session file it generates for me has a copy of the event it belonged to as well
